[project]
name = "ln_workflows"
version = "0.0.0"
description = "Containerized applications for quantum chemistry workflow management"
authors = [
    {name = "Felix Rotter-McCartney",email = "felix.rotter@mail.utoronto.ca"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<3.15,!=3.14.1"
dependencies = [
    "maggma (>=0.74.0,<0.75.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "typer (>=0.27.1,<0.28.0)",
    "dask (>=2026.7.1,<2027.0.0)",
    "types-networkx (>=3.6.1.20260728,<4.0.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "pydantic-core (>=2.48.0,<3.0.0)",
    "orca-pi (>=2.0.0,<3.0.0)",
]

[project.scripts]
lnwctl = "ln_workflows.cli.lnwctl:app"

[tool.poetry]
packages = [{ include = "ln_workflows", from = "src" }]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
commit_parser = "conventional"
build_command = "pip install build && python -m build --sdist --wheel ."

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[dependency-groups]
dev = [
    "ruff (>=0.16.1,<0.17.0)",
    "ty (>=0.0.65,<0.0.66)",
    "python-semantic-release (>=10.6.1,<11.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
